### ISSUE TITLE
Make blog categories more useful

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#18]
Show categories for each blog post

**Comment by aileennoonan** [comment]
This works well now John. The only thing is that when I put in four categories and therefore making it two lines of categories, it looks a bit squished (the second line is snuggled up too close to the first line). Have a look at Feeling Dizzy and you will see what I mean. 

Also, if it's an easy thing to do (and don't worry if it's not) but I'd make the categories smaller font size. At the moment they are almost catching the eye more than the blurb.

**Comment by aileennoonan** [comment]
How hard would it be to have a 'Hot Topics' list to the right hand side which lists the categories so people can actually search by category? Here is an example of what I mean : 
![image](https://user-images.githubusercontent.com/25756782/26999279-174ca21c-4dd9-11e7-89d3-2b9c9c9e8d71.png)

**Comment by 1001hz** [comment]
Have a look at this, see what you think. Also changed font size and put spacing when they run onto 2 lines

**Comment by aileennoonan** [comment]
This all looks great but do you think that the hot topics could be wide enough to handle two words like 'Neurological Rehabilitation' without going down to a second line?

**Comment by aileennoonan** [comment]
When you click into a blog post, the hot topics is very close and snuggled up to the main content. Any chance of moving it a bit farther right?

**Comment by 1001hz** [comment]
Made the spacing between left and right cols (that's called the gutter) bigger. Making it even bigger again will cause the long category name to wrap onto 2 lines again. Not so much of a problem because I changed the style a bit for the case where it might wrap to look a bit better. Let me know if you want the gutter bigger and if not then we can close.

**Comment by aileennoonan** [comment]
No this is good.. the blog is a lot more useful now. 

Just as a final thing.. can you make the spacing smaller between Blog and the first post and between the first post and the second post and so on. The gaps are just a bit too big right now.

**Comment by 1001hz** [comment]
Changed up the spacing so have a look. Also I changed the secondary headings to be the dark grey color instead of blue because "Blog" was getting lost as the page heading when the blog headings were also blue. You know what I mean? Anyway, have a look and hit me back, just to chat, truly yours, your biggest fan, this is Stan.

**Comment by aileennoonan** [comment]
I'm very happy with this now.. it looks great and you were spot on with changing the colour of the secondary headings.
