### ISSUE TITLE
Why is the 'Feeling Dizzy' blog post opening up the About Us page?

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#20]
Really odd.. it's not doing it in the CMS. I think this is a similar problem to the Staff being broken under 'About Us'. Really sorry.. I defo screwed the pooch yesterday when I was playing around :/

**Comment by 1001hz** [comment]
Reason: Both about us and feeling dizzy somehow had the same url: '46.101.18.73/lorem-ipsum/'. It's easy to change the URL in the edit blog page. It's the permalink field right under the title. I've changed both now because 'lorem-ipsum' shouldn't be anywhere on the live site. Must have got in there from a test page I created. All should be good now. I'll close if you're happy.

**Comment by aileennoonan** [comment]
Thanks John!
