### ISSUE TITLE
Book an appointment - a few questions (not issues!)

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#24]
Hey John,

When you click book an appointment and the pop up box pops open, do you ever foresee a problem if someone has pop ups blocked on their computer. 

Also, I need to add in a line of text 'Appointments are subject to availability' but I can't find that functionality on the form builder. If you have any ideas, that would be great. 

Finally.. do you have any advice about putting in an anti spam line? No bother if you don't.. I can do some research.

**Comment by 1001hz** [comment]
No problem with pop ups because the form isn't a new window; it's just a hidden element on the page that becomes visible. Pop up blocker won't stop it and neither would something like an add blocker. It's a standard way of showing what's called a 'modal'

I've made it so the text area of the content page will show info on the top of the form.

The forms plugin we're using (Ninja Forms) has functionality for anti spam (like answer 1 + 3 question). I wouldn't use it unless you need it. See what your research recommends. It's a trade off between UX and security.

**Comment by aileennoonan** [comment]
Great, thanks. I agree re: the anti spam. I think we will see how it goes over the first few months and whether they are getting a lot of crap through or not. If they aren't I won't bother with it. 

How to I get to the text area of the content page? Book an appointment doesn't have a content page... or does it?

**Comment by aileennoonan** [comment]
Figured this out. Closing it now!
